# Generated by Django 4.0 on 2021-12-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='alimento_extrafortificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alimento',
            name='alimento_fortificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alimento',
            name='cero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alimento',
            name='consolutar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alimento',
            name='nuevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alimento',
            name='trazas',
            field=models.BooleanField(default=False),
        ),
    ]
