# Generated by Django 4.0 on 2022-04-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alimento_alimento_extrafortificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.categoria'),
        ),
    ]
